export const FETCH_APPLY_FOR_COUNCIL = "FETCH_APPLY_FOR_COUNCIL";
export const LISTEN_APPLY_FOR_COUNCIL = "LISTEN_APPLY_FOR_COUNCIL";
export const ASSIGN_MEDIATOR_FOR_COUNCIL = "ASSIGN_MEDIATOR_FOR_COUNCIL";

