export const CREATE_APPLY_FOR_CITIZEN = "CREATE_APPLY_FOR_CITIZEN";
export const UPDATE_APPLY_FOR_CITIZEN = "UPDATE_APPLY_FOR_CITIZEN";
export const FETCH_APPLY_FOR_CITIZEN = "FETCH_APPLY_FOR_CITIZEN";
export const LISTEN_APPLY_FOR_CITIZEN = "LISTEN_APPLY_FOR_CITIZEN";
export const DELETE_APPLY_FOR_CITIZEN = "DELETE_APPLY_FOR_CITIZEN";

