export const CREATE_MEDIATOR = "CREATE_MEDIATOR";
export const UPDATE_MEDIATOR = "UPDATE_MEDIATOR";
export const DELETE_MEDIATOR = "DELETE_MEDIATOR";
export const LISTEN_MEDIATOR = "LISTEN_MEDIATOR";
export const FETCH_MEDIATOR  = "FETCH_MEDIATOR";



