export const CREATE_MEDIATOR_FOR_COUNCIL = "CREATE_MEDIATOR_FOR_COUNCIL";
export const UPDATE_MEDIATOR_FOR_COUNCIL = "UPDATE_MEDIATOR_FOR_COUNCIL";
export const DELETE_MEDIATOR_FOR_COUNCIL = "DELETE_MEDIATOR_FOR_COUNCIL";
export const LISTEN_MEDIATOR_FOR_COUNCIL = "LISTEN_MEDIATOR_FOR_COUNCIL";
export const FETCH_MEDIATOR_FOR_COUNCIL  = "FETCH_MEDIATOR_FOR_COUNCIL";



