export const FETCH_APPLY_FOR_MEDIATOR = "FETCH_APPLY_FOR_MEDIATOR";
export const LISTEN_APPLY_FOR_MEDIATOR = "LISTEN_APPLY_FOR_MEDIATOR";
export const REJECT_APPLY_FOR_MEDIATOR = "REJECT_APPLY_FOR_MEDIATOR";
export const APPROVE_APPLY_FOR_MEDIATOR = "APPROVE_APPLY_FOR_MEDIATOR";

