export const FETCH_PROFESSION = "FETCH_PROFESSION";
export const FETCH_INSTITUTION = "FETCH_INSTITUTION";
export const FETCH_DISTRICT = "FETCH_DISTRICT";
export const FETCH_SOCIAL_MEDIA = "FETCH_SOCIAL_MEDIA";
export const FETCH_OFFICE = "FETCH_OFFICE";
export const FETCH_PERSON = "FETCH_PERSON";
export const CREATE_MEDIATR = "CREATE_MEDIATR";









